#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_imma_tf="0.0.1"
  jq -n --arg imma_tf "$ver_imma_tf" '{imma_tf: $imma_tf}'
}

version "$@"
